### ISSUE TITLE
Git FETCH_HEAD

### ISSUE THREAD

**Issue by juliohm** [invenia/PkgTemplates.jl#8]
Every project I create with PkgTemplates.jl shows the following message whenever I do a git pull:

> * branch            master     -> FETCH_HEAD
>Already up-to-date.

Even though all the objected have been fetched, the message keeps appearing on every pull. What is done differently than PkgDev.jl, I don't get this message when I create the package with their generate() method.

**Comment by juliohm** [comment]
Any idea of what is happening?

**Comment by christopher-dG** [comment]
Sorry, I have not had time to look at this. I'll try to get to it this weekend.

**Comment by juliohm** [comment]
I've added the following line to the `.git/config` of the repository and the problem was solved:

```
	fetch = +refs/heads/*:refs/remotes/origin/*
```

This line should be placed in the section `origin` (the GitHub clone), although I don't understand what it means:

```
[core]
	bare = false
	repositoryformatversion = 0
	filemode = true
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:juliohm/LocallyWeightedRegression.jl
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = git@github.com:juliohm/LocallyWeightedRegression.jl
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

How PkgTemplates.jl differs from PkgDev.jl when it comes to Git?

**Comment by christopher-dG** [comment]
Okay, this should be at least partially fixed. I think you need to set your upstream branch (`git push origin master -u`) to get rid of the `FETCH_HEAD` thing. Let me know if that works!

**Comment by juliohm** [comment]
You mean that PkgDev.jl also generated the same FETCH_HEAD message upon git pulls?

**Comment by christopher-dG** [comment]
Correct, yet. Either way, the remote is now set identically to `PkgDev`.

**Comment by juliohm** [comment]
I don't remember seeing this issue in a while, it should be fixed, thanks :blush:
